/*
 * 天子蒙尘：献帝模拟器 v2.13.0
 * 游戏数据：人物、势力、事件与行动说明
 * 本作是历史题材架空模拟，数值与事件均经过游戏化处理。
 */

window.GAME_DATA = {
  version: "2.13.0",
  title: "天子蒙尘：献帝模拟器",
  scenarios: [
    {
      id: "zhongping_189", name: "中平六年·洛阳孤灯", era: "中平", startYear: 189, startMonth: 9, maxTurns: 18,
      difficulty: "危局", recordTitle: "中平实录",
      summary: "董卓入京前后的权力真空。先保住天子与百官，再设法离开洛阳。",
      intro: "中平六年，洛阳宫阙仍在，朝局却已失去支点。外兵将入京，宗室与百官各怀忧惧。你必须在少年天子的有限名分下，先保存宫禁与朝廷骨架。",
      opening: "中平六年九月，京师兵变传闻四起。天子临朝，命百官暂守宫门与尚书台。",
      statModifiers: { authority: -8, prestige: 8, security: -12, treasury: 6, officials: -4, caoAlert: -18 },
      hiddenModifiers: { loyalNetwork: -5, leakRisk: 8, peopleStability: -7, externalBalance: 5, escapeRoute: 8 },
      cityOverrides: { luoyang: { controller: "court", controllerName: "汉廷", defense: 48, supply: 52, courtLoyalty: 90 }, xudu: { controller: "fragmented", controllerName: "颍川郡县", courtLoyalty: 58 } },
      armyModifiers: { courtMultiplier: 1.35, generalMultiplier: .72, supplyDelta: -8 },
      challenge: { title: "洛阳孤灯", description: "坚持至剧本结束，并使宫廷安全与皇权都不低于 40。", statMin: { security: 40, authority: 40 } },
    },
    {
      id: "xingping_195", name: "兴平二年·天子东归", era: "兴平", startYear: 195, startMonth: 8, maxTurns: 18,
      difficulty: "艰难", recordTitle: "兴平实录",
      summary: "长安失序，车驾东归。以残破朝廷穿过关中与河洛，寻找新的立足点。",
      intro: "兴平二年，长安饥乱，护驾诸将争权。车驾东归的每一步都需要粮秣、名分与临时盟友。你要把流亡朝廷带回关东，而不是让百官在途中离散。",
      opening: "兴平二年八月，车驾议定东归。百官扶老携幼，沿途关隘与粮道皆未可知。",
      statModifiers: { authority: -5, prestige: 4, security: -8, treasury: -15, officials: -8, caoAlert: -10 },
      hiddenModifiers: { loyalNetwork: 4, leakRisk: 4, peopleStability: -5, externalBalance: 4, escapeRoute: 16 },
      cityOverrides: { changan: { controller: "fragmented", controllerName: "护驾诸将", defense: 45, supply: 18, courtLoyalty: 72 }, luoyang: { defense: 25, supply: 12, courtLoyalty: 80 } },
      armyModifiers: { courtMultiplier: .72, generalMultiplier: .82, supplyDelta: -12 },
      challenge: { title: "衣冠东归", description: "坚持至剧本结束，汉室威望不低于 58、国库不低于 20。", statMin: { prestige: 58, treasury: 20 } },
    },
    {
      id: "jianan_196", name: "建安元年·许都", era: "建安", startYear: 196, startMonth: 10, maxTurns: 24,
      difficulty: "标准", recordTitle: "建安实录",
      summary: "天子迁许。依靠诏书、官爵与制衡，在曹氏军政保护下恢复朝廷。",
      intro: "你是大汉天子刘协。洛阳残破，百官饥困，曹操迎驾迁许。你仍握有诏书、官爵与汉室名分，却缺少军队、财赋和可信赖的执行者。未来二十四个月，你必须在依附与自救之间维持汉祚。",
      opening: "建安元年十月，天子迁驻许都。宫室未备，百官饥困，汉廷在曹氏军政保护下重新开朝。",
      statModifiers: {}, hiddenModifiers: {}, cityOverrides: {}, armyModifiers: { courtMultiplier: 1, generalMultiplier: 1, supplyDelta: 0 },
      challenge: { title: "许都自立", description: "坚持至剧本结束，皇权不低于 55且曹氏警戒低于 82。", statMin: { authority: 55 }, statMax: { caoAlert: 81 } },
    },
    {
      id: "jianan_200", name: "建安五年·官渡风云", era: "建安", startYear: 200, startMonth: 1, maxTurns: 18,
      difficulty: "权衡", recordTitle: "官渡实录",
      summary: "曹袁决战在即。朝廷名义成为双方都想争取的战略资源。",
      intro: "建安五年，曹操与袁绍隔河对峙。许都朝廷既是曹氏后方，也是河北争夺的名分。你可以借大战扩大政治空间，但任何误判都会使宫廷先于战线崩溃。",
      opening: "建安五年正月，河北军书与许都急报同时入朝。天子命尚书台分别答复，不许一方独占汉廷名义。",
      statModifiers: { authority: 4, prestige: 2, security: 2, treasury: 3, officials: 3, caoAlert: 14 },
      hiddenModifiers: { loyalNetwork: 3, leakRisk: 5, peopleStability: 2, externalBalance: 18, escapeRoute: -2 },
      cityOverrides: { ye: { defense: 90, supply: 92 }, xudu: { defense: 85, supply: 86 }, linzi: { controller: "yuan_shao", controllerName: "袁绍", defense: 70 } },
      armyModifiers: { courtMultiplier: 1.08, generalMultiplier: 1.18, supplyDelta: 5 },
      challenge: { title: "两雄之间", description: "坚持至剧本结束，外部制衡不低于 52且曹氏警戒低于 88。", hiddenMin: { externalBalance: 52 }, statMax: { caoAlert: 87 } },
    },
    {
      id: "yankang_220", name: "延康元年·禅代前夜", era: "延康", startYear: 220, startMonth: 1, maxTurns: 12,
      difficulty: "绝境", recordTitle: "延康实录",
      summary: "旧秩序只剩最后一年。用十二个月争取一条不由他人书写的终局。",
      intro: "延康元年，曹操已逝，魏王府要求重新确认朝廷与藩国的关系。百官多已接受改朝换代不可避免。你只有十二个月，把汉室最后的名分变成谈判筹码。",
      opening: "延康元年正月，魏王府使者入朝。禅代之议尚未公开，百官的沉默却比奏疏更响。",
      statModifiers: { authority: -10, prestige: -8, security: 3, treasury: 8, officials: -12, caoAlert: 22 },
      hiddenModifiers: { loyalNetwork: -8, leakRisk: 10, peopleStability: 8, externalBalance: -6, escapeRoute: 10 },
      cityOverrides: { xudu: { controller: "cao_cao", controllerName: "魏王府", defense: 92, supply: 94, courtLoyalty: 48 }, ye: { controller: "cao_cao", controllerName: "魏王府", defense: 92, supply: 95, courtLoyalty: 20 }, xiapi: { controller: "cao_cao", controllerName: "魏王府" }, shouchun: { controller: "cao_cao", controllerName: "魏王府" } },
      armyModifiers: { courtMultiplier: .62, generalMultiplier: 1.32, supplyDelta: 10 },
      challenge: { title: "不失天子体面", description: "坚持至剧本结束，汉室威望不低于 55、皇权不低于 38。", statMin: { prestige: 55, authority: 38 } },
    },
  ],
  scenario: {
    name: "建安元年·许都",
    startYear: 196,
    startMonth: 10,
    maxTurns: 24,
    intro:
      "你是大汉天子刘协。洛阳残破，百官饥困，曹操迎驾迁许。你仍握有诏书、官爵与汉室名分，却缺少军队、财赋和可信赖的执行者。未来二十四个月，你必须在依附与自救之间维持汉祚。",
  },

  scenarioEvents: {
    zhongping_189: {
      id: "scenario_189_opening", title: "京师兵权", category: "危局",
      text: "外军将至，宫门守备各奉不同号令。百官请天子立即确定京师兵权归属，以免宫禁先乱。",
      choices: [
        { label: "宿卫归尚书台节制", hint: "提高皇权，但执行困难。", effects: { authority: 7, security: 2, officials: 3 }, hidden: { loyalNetwork: 3, leakRisk: 2 }, chronicle: "天子诏宿卫归尚书台节制，力图以朝命约束京师兵权。" },
        { label: "分守宫门，各不相扰", hint: "换取短暂安全。", effects: { security: 7, authority: -2, officials: 1 }, chronicle: "宫门分区守备，京师暂未因号令冲突而生乱。" },
        { label: "预备东出洛阳", hint: "增加退路，宫中流言上升。", effects: { security: -2, prestige: 3 }, hidden: { escapeRoute: 9, leakRisk: 5 }, chronicle: "天子暗命近臣勘察东出道路，为最坏局面预留退路。" },
      ],
    },
    xingping_195: {
      id: "scenario_195_opening", title: "东归第一程", category: "行在",
      text: "车驾将离长安，现有粮车不足以同时供给百官与护驾军。沿途关隘又要求出示不同将领的通行文书。",
      choices: [
        { label: "先保百官家属", hint: "官心与名望上升，行军更险。", effects: { officials: 7, prestige: 5, security: -4, treasury: -3 }, chronicle: "东归首程先载百官家属，行在虽慢，衣冠未散。" },
        { label: "粮车尽归护驾军", hint: "安全上升，百官失望。", effects: { security: 8, officials: -5, treasury: 2 }, chronicle: "粮车优先供给护驾诸军，车驾得行，随从多有饥色。" },
        { label: "沿途以官爵换粮", hint: "补充国库，透支朝廷名分。", effects: { treasury: 9, prestige: -5, authority: -2 }, hidden: { externalBalance: 4 }, chronicle: "行在以官爵换取沿途粮秣，暂渡危局，也留下日后追认之债。" },
      ],
    },
    jianan_200: {
      id: "scenario_200_opening", title: "官渡两表", category: "军国",
      text: "曹袁两方奏表同日抵达：一方请诏河北为逆，一方请罢曹操权柄。任何明确表态都会把朝廷押上战线。",
      choices: [
        { label: "两表并留，不判逆顺", hint: "强化制衡，双方都不满意。", effects: { authority: 3, caoAlert: 4, security: -2 }, hidden: { externalBalance: 9 }, chronicle: "天子将曹袁两表并留尚书台，暂不以朝命判定逆顺。" },
        { label: "诏诸军以安民为先", hint: "提升名望，实际约束有限。", effects: { prestige: 7, officials: 3, treasury: -2 }, hidden: { peopleStability: 4 }, chronicle: "朝廷不论曹袁名位，先诏两军保全沿线百姓与漕运。" },
        { label: "支持许都军令", hint: "短期更安全，外部制衡下降。", effects: { security: 8, caoAlert: -7, authority: -4 }, hidden: { externalBalance: -7 }, chronicle: "朝廷支持许都军令，官渡战事遂以曹氏名义统一调度。" },
      ],
    },
    yankang_220: {
      id: "scenario_220_opening", title: "禅代试表", category: "终局",
      text: "魏王府送来一份未署名的禅代试表，请尚书台先议礼仪与百官次序。它不是正式逼迫，却在等待天子的态度。",
      choices: [
        { label: "封还试表，不议禅代", hint: "维护皇权，警戒大幅上升。", effects: { authority: 8, prestige: 6, security: -7, caoAlert: 10 }, chronicle: "天子封还禅代试表，命尚书台不得先议改朝礼仪。" },
        { label: "只议宗庙与百官保全", hint: "为退路争取条件。", effects: { authority: 2, prestige: 3, security: 3, caoAlert: 3 }, hidden: { escapeRoute: 7 }, chronicle: "朝廷未应禅代，只命使者先明示宗庙与百官如何保全。" },
        { label: "允尚书台预备礼仪", hint: "宫廷安全上升，汉廷威望受损。", effects: { security: 9, caoAlert: -8, authority: -8, prestige: -7, treasury: 5 }, chronicle: "尚书台奉命预备改朝礼仪，宫门平静，朝臣却知终局已近。" },
      ],
    },
  },

  statMeta: {
    authority: {
      name: "皇权",
      icon: "玺",
      description: "诏令被执行的能力。过低时，百官和地方势力会公开拖延甚至抗命。",
      goodHigh: true,
    },
    prestige: {
      name: "汉室威望",
      icon: "汉",
      description: "天下对朝廷正统性的认可。它是你最重要、也最容易被透支的政治资本。",
      goodHigh: true,
    },
    security: {
      name: "宫廷安全",
      icon: "禁",
      description: "皇帝、后宫与近臣的安全。过低可能导致监控、软禁或密谋败露。",
      goodHigh: true,
    },
    treasury: {
      name: "国库",
      icon: "帑",
      description: "朝廷可实际调动的钱粮充盈度。赈济、赏赐、仪典与秘密活动都会消耗它。",
      goodHigh: true,
    },
    officials: {
      name: "百官支持",
      icon: "臣",
      description: "官僚群体愿意替你承担风险、执行命令的程度。",
      goodHigh: true,
    },
    caoAlert: {
      name: "曹氏警戒",
      icon: "疑",
      description: "曹操集团对你恢复实权的戒备。过高会触发监控与清洗；过低也可能意味着你已无足轻重。",
      goodHigh: false,
    },
  },

  factions: [
    {
      id: "imperial",
      name: "皇帝与后宫",
      short: "宫中",
      color: "#d9b45b",
      description: "以皇帝、皇后和近侍为核心，目标是保全宗庙并逐步恢复自主权。",
    },
    {
      id: "han_loyalists",
      name: "汉室旧臣",
      short: "旧臣",
      color: "#9c3f3f",
      description: "重视礼制与大汉正统，但能力、胆量和现实利益各不相同。",
    },
    {
      id: "cao_group",
      name: "曹氏集团",
      short: "曹氏",
      color: "#4f6070",
      description: "控制军事、政务和许都秩序，同时需要利用汉廷名义号令天下。",
    },
    {
      id: "xu_officials",
      name: "许都官僚",
      short: "许官",
      color: "#6e6a58",
      description: "首先考虑职位、家族和秩序，往往随局势选择立场。",
    },
    {
      id: "regional_lords",
      name: "地方诸侯",
      short: "诸侯",
      color: "#456d69",
      description: "尊奉朝廷可以带来合法性，但没有人愿意无条件服从。",
    },
    {
      id: "gentry_people",
      name: "士族与百姓",
      short: "民间",
      color: "#7a6d46",
      description: "关心税赋、粮价和安定，也会影响地方官与诸侯的选择。",
    },
  ],

  characters: [
    {
      id: "liu_xie",
      name: "刘协",
      title: "大汉天子",
      faction: "imperial",
      initials: "帝",
      profile: "少年即位，历经董卓、李傕、郭汜之乱。你拥有法统，却必须学习如何把名分转化为真实权力。",
      publicTraits: ["敏锐", "克制", "善记"],
      relation: 100,
      influence: 40,
    },
    {
      id: "empress_fu",
      name: "伏皇后",
      title: "皇后",
      faction: "imperial",
      initials: "伏",
      profile: "与你共历流离。她关心宫中安全，也可能成为联络外戚与忠臣的纽带。",
      publicTraits: ["谨慎", "坚忍", "护持宗室"],
      relation: 78,
      influence: 34,
    },
    {
      id: "dong_cheng",
      name: "董承",
      title: "车骑将军",
      faction: "han_loyalists",
      initials: "董",
      profile: "曾护送天子东归，愿意为汉室冒险，但行动越激进，泄密风险越高。",
      publicTraits: ["忠汉", "果决", "好险"],
      relation: 66,
      influence: 54,
    },
    {
      id: "yang_biao",
      name: "杨彪",
      title: "太尉",
      faction: "han_loyalists",
      initials: "杨",
      profile: "名望深厚的老臣，精于礼法，反对越制，但不会轻易把家族置于绝境。",
      publicTraits: ["持重", "守礼", "名望高"],
      relation: 58,
      influence: 62,
    },
    {
      id: "xun_yu",
      name: "荀彧",
      title: "尚书令",
      faction: "cao_group",
      initials: "荀",
      profile: "主持中枢政务，重视汉室秩序与人才治理，同时是曹操最倚重的谋臣之一。",
      publicTraits: ["清雅", "务实", "重秩序"],
      relation: 50,
      influence: 78,
    },
    {
      id: "cao_cao",
      name: "曹操",
      title: "司空·录尚书事",
      faction: "cao_group",
      initials: "曹",
      profile: "掌握军队与政务，是朝廷的保护者，也是皇权最大的现实约束。",
      publicTraits: ["果断", "多疑", "爱才"],
      relation: 42,
      influence: 96,
    },
    {
      id: "yuan_shao",
      name: "袁绍",
      title: "冀州牧",
      faction: "regional_lords",
      initials: "绍",
      profile: "门生故吏遍天下，控制河北。愿意借汉室名义，但不会轻易接受许都节制。",
      publicTraits: ["门第显赫", "重名望", "迟疑"],
      relation: 44,
      influence: 88,
    },
    {
      id: "yuan_shu",
      name: "袁术",
      title: "后将军",
      faction: "regional_lords",
      initials: "术",
      profile: "占据淮南，拥有兵粮和野心，对汉室名分既觊觎又轻视。",
      publicTraits: ["骄矜", "奢侈", "野心外露"],
      relation: 24,
      influence: 69,
    },
    {
      id: "liu_biao",
      name: "刘表",
      title: "荆州牧",
      faction: "regional_lords",
      initials: "表",
      profile: "汉室宗亲，坐镇荆州，倾向维持秩序，但更重视本州安全。",
      publicTraits: ["守成", "重文士", "顾全宗族"],
      relation: 57,
      influence: 73,
    },
    {
      id: "sun_ce",
      name: "孙策",
      title: "讨逆将军",
      faction: "regional_lords",
      initials: "策",
      profile: "正在江东迅速扩张，渴望朝廷承认与官爵，也可能成为牵制淮南的新力量。",
      publicTraits: ["锐进", "重信用", "年轻气盛"],
      relation: 39,
      influence: 63,
    },
  ],

  actionCatalog: [
    {
      id: "edict",
      name: "拟写圣旨",
      icon: "诏",
      category: "statecraft",
      description: "自由输入命令，由本地规则解析为赈济、任官、外交、调查、整军或礼制行动。",
    },
    {
      id: "audience",
      name: "召见人物",
      icon: "召",
      category: "domestic",
      description: "选择一名人物私下或公开召见，改善关系并获取政治反馈。",
    },
    {
      id: "appointment",
      name: "任免封赏",
      icon: "官",
      category: "domestic",
      description: "以官职和爵位交换支持。可提升皇权，但容易引发曹氏警戒。",
    },
    {
      id: "secret",
      name: "密令联络",
      icon: "密",
      category: "intrigue",
      description: "扩大忠汉网络，代价是增加泄密风险与宫廷危险。",
    },
    {
      id: "revenue",
      name: "筹措钱粮",
      icon: "计",
      category: "finance",
      description: "补充国库。可核减冗费、催办贡赋或向司空府借调，各有政治代价。",
    },
    {
      id: "relief",
      name: "赈济减赋",
      icon: "民",
      category: "finance",
      description: "消耗国库换取威望与民间稳定，执行效果受皇权影响。",
    },
    {
      id: "ritual",
      name: "整饬朝仪",
      icon: "礼",
      category: "domestic",
      description: "利用礼制、祭祀与朝会强化汉廷存在感。",
    },
    {
      id: "appease",
      name: "安抚曹氏",
      icon: "和",
      category: "diplomacy",
      description: "降低警戒、换取安全与资源，但可能削弱你的独立形象。",
    },
    {
      id: "regional",
      name: "结交外镇",
      icon: "使",
      category: "diplomacy",
      description: "联络地方诸侯，以朝廷名义制造外部制衡。",
    },
  ],

  fixedEvents: [
    {
      id: "arrival_xu",
      fixedTurn: 1,
      title: "许都新廷",
      category: "朝政",
      text:
        "百官随驾至许，宫室仓促，粮秣不足。曹操请以许县为治所，并由其属官统筹宿卫、粮运与尚书台事务。百官等待你的第一道正式诏令。",
      choices: [
        {
          label: "准其统筹，以安朝廷",
          hint: "安全与国库改善，但皇权受限。",
          effects: { security: 8, treasury: 6, authority: -4, caoAlert: -6 },
          relations: { cao_cao: 6, xun_yu: 4 },
          chronicle: "天子准司空统筹许都庶务，朝廷稍安，军政权柄进一步归于曹氏。",
        },
        {
          label: "设御前署，军政分理",
          hint: "尝试保留中枢权力，会提高警戒。",
          effects: { authority: 7, officials: 4, security: -3, caoAlert: 8 },
          relations: { yang_biao: 4, cao_cao: -4 },
          chronicle: "天子命御前署与司空府分理庶务，百官见皇权尚有自振之意。",
        },
        {
          label: "先议赈粮，不争名目",
          hint: "以民生为先，威望增加。",
          effects: { prestige: 6, treasury: -4, officials: 3, caoAlert: 1 },
          relations: { xun_yu: 3, empress_fu: 2 },
          chronicle: "天子不争署名，先命开仓济百官与流民，许都人心稍定。",
        },
      ],
    },
    {
      id: "seal_and_edicts",
      fixedTurn: 3,
      title: "玺书归属",
      category: "制度",
      text:
        "尚书台奏请：今后诏书草拟、用玺、传驿均应有固定程式。曹氏官员主张先送司空府核验，以免伪诏；杨彪则坚持玺书不可受外府节制。",
      choices: [
        {
          label: "诏书先经尚书台，不送司空府",
          hint: "强化制度独立，风险较高。",
          effects: { authority: 9, officials: 3, caoAlert: 10, security: -2 },
          relations: { yang_biao: 6, xun_yu: -2, cao_cao: -5 },
          chronicle: "天子定制，诏书经尚书台用玺，不许外府先行核验。",
        },
        {
          label: "军务核验，民政直出",
          hint: "折中方案。",
          effects: { authority: 4, security: 3, caoAlert: 3, officials: 2 },
          relations: { xun_yu: 4, yang_biao: 2 },
          chronicle: "朝廷定军务诏令与民政诏令分途，暂缓玺书之争。",
        },
        {
          label: "从司空府议，以防伪诏",
          hint: "安全提高，但皇权下降。",
          effects: { security: 7, caoAlert: -7, authority: -7, treasury: 3 },
          relations: { cao_cao: 7, xun_yu: 3 },
          chronicle: "天子准诏书先经司空府核验，许都法令归一，皇权更受掣肘。",
        },
      ],
    },
    {
      id: "yuan_shu_ambition",
      fixedTurn: 5,
      title: "淮南异议",
      category: "天下",
      text:
        "淮南传来消息：袁术僭越礼制，搜罗符瑞，属吏多以帝号相劝。朝廷应否先发严诏，天下诸侯皆在观望。",
      choices: [
        {
          label: "立即斥其僭越，号召共讨",
          hint: "维护正统，但可能过度依赖曹操出兵。",
          effects: { prestige: 10, authority: 4, treasury: -2, caoAlert: 3 },
          relations: { yuan_shu: -18, cao_cao: 4, sun_ce: 5, yuan_shao: 3 },
          chronicle: "朝廷严诏斥袁术僭越，令诸侯奉汉讨逆。",
        },
        {
          label: "先派使者申诫，留其退路",
          hint: "较稳妥，但威望增长有限。",
          effects: { prestige: 4, security: 2, authority: 1 },
          relations: { yuan_shu: -6, liu_biao: 2 },
          chronicle: "天子遣使淮南申诫袁术，尚未明发讨伐之诏。",
        },
        {
          label: "秘许孙策官爵，令其牵制",
          hint: "建立外部力量，警戒与泄密风险增加。",
          effects: { prestige: 3, authority: 3, caoAlert: 7, security: -3 },
          hidden: { loyalNetwork: 5, leakRisk: 6, externalBalance: 10 },
          relations: { sun_ce: 12, yuan_shu: -10, cao_cao: -2 },
          chronicle: "朝廷密许孙策官爵，欲借江东之锐牵制淮南。",
        },
      ],
    },
    {
      id: "palace_guard",
      fixedTurn: 7,
      title: "宿卫名籍",
      category: "宫禁",
      text:
        "伏皇后发现宫门宿卫名籍多由司空府直接更换，宫中旧侍被逐渐调离。董承建议秘密安插可信之人，荀彧则称统一调度可防刺客。",
      choices: [
        {
          label: "秘密安插旧侍",
          hint: "增强忠诚网络，但泄密风险明显上升。",
          effects: { security: 4, caoAlert: 9 },
          hidden: { loyalNetwork: 10, leakRisk: 9 },
          relations: { dong_cheng: 7, empress_fu: 5, cao_cao: -4 },
          chronicle: "宫中暗置旧侍，宿卫之内渐有天子可信之人。",
        },
        {
          label: "接受统一宿卫，另设内廷值班",
          hint: "折中，安全较稳。",
          effects: { security: 7, authority: 2, caoAlert: 2 },
          hidden: { loyalNetwork: 3 },
          relations: { xun_yu: 3, empress_fu: 2 },
          chronicle: "天子接受统一宿卫，同时保留内廷值班小署。",
        },
        {
          label: "完全交由司空府",
          hint: "短期最安全，但宫廷自主权下降。",
          effects: { security: 10, caoAlert: -8, authority: -6, officials: -2 },
          relations: { cao_cao: 6, dong_cheng: -5 },
          chronicle: "宫门宿卫尽归司空府调度，刺客难入，天子亦难自主出入。",
        },
      ],
    },
    {
      id: "northern_envoy",
      fixedTurn: 9,
      title: "河北来使",
      category: "外交",
      text:
        "袁绍遣使入朝，表面奉问起居，实则请求提高官爵，并暗示河北愿意保护汉室。曹操主张以虚衔安抚，不可使其借朝命扩大声势。",
      choices: [
        {
          label: "加其官爵，换取公开奉汉",
          hint: "威望和外部制衡上升，也会刺激曹氏。",
          effects: { prestige: 6, authority: 2, caoAlert: 8 },
          hidden: { externalBalance: 9 },
          relations: { yuan_shao: 12, cao_cao: -5 },
          chronicle: "朝廷加袁绍官爵，河北公开奉表称臣，许都对此戒心大增。",
        },
        {
          label: "只赐诏书，不增实职",
          hint: "温和维持关系。",
          effects: { prestige: 3, authority: 1, caoAlert: 1 },
          relations: { yuan_shao: 4, xun_yu: 2 },
          chronicle: "天子赐玺书慰劳袁绍，未许其实职所请。",
        },
        {
          label: "令其先贡粮入朝",
          hint: "有机会增加国库，但可能激怒河北。",
          effects: { treasury: 8, prestige: -2, authority: 3 },
          relations: { yuan_shao: -7, cao_cao: 3 },
          chronicle: "朝廷令袁绍先贡粮入许，河北使者不悦而退。",
        },
      ],
    },
    {
      id: "xun_yu_memorial",
      fixedTurn: 11,
      title: "尚书令密奏",
      category: "人物",
      text:
        "荀彧密奏：朝廷若欲恢复威信，应先使法令清明、赋役有度，而非急于结党。他愿替你整顿尚书台，但要求停止绕过中枢的秘密诏令。",
      choices: [
        {
          label: "采纳其议，整顿尚书台",
          hint: "百官与皇权提升，忠汉网络扩张放缓。",
          effects: { authority: 7, officials: 8, caoAlert: -2, treasury: -3 },
          hidden: { loyalNetwork: -3, leakRisk: -5 },
          relations: { xun_yu: 10, dong_cheng: -3 },
          chronicle: "天子命荀彧整顿尚书台，法令渐有条理，密诏活动暂缓。",
        },
        {
          label: "表面采纳，暗中保留密线",
          hint: "收益均衡，但一旦泄露后果较重。",
          effects: { authority: 4, officials: 4, caoAlert: 3 },
          hidden: { loyalNetwork: 4, leakRisk: 5 },
          relations: { xun_yu: 3, dong_cheng: 2 },
          chronicle: "天子采纳尚书台整顿之议，暗中仍保留数条密线。",
        },
        {
          label: "拒绝，不使曹氏掌握诏令",
          hint: "维护自主性，但官僚支持下降。",
          effects: { authority: 3, officials: -7, caoAlert: 7, security: -2 },
          relations: { xun_yu: -9, dong_cheng: 5 },
          chronicle: "天子拒绝尚书令所请，朝廷内外诏令更显分歧。",
        },
      ],
    },
    {
      id: "wan_crisis",
      fixedTurn: 13,
      title: "宛城急报",
      category: "军事",
      text:
        "南阳战事失利，许都震动。曹氏将领请求朝廷追赠死者、征发粮械，并压制传播败讯的议论。此时曹操对汉廷名义的需要上升。",
      choices: [
        {
          label: "厚加追赠，公开慰军",
          hint: "改善曹氏关系，消耗国库。",
          effects: { security: 5, treasury: -7, caoAlert: -7, prestige: 2 },
          relations: { cao_cao: 8, xun_yu: 4 },
          chronicle: "朝廷厚加追赠，遣使慰军，许都军心稍定。",
        },
        {
          label: "追赠之外，要求军务定期上奏",
          hint: "趁机争取监督权。",
          effects: { authority: 8, treasury: -4, caoAlert: 8, officials: 3 },
          relations: { cao_cao: -5, yang_biao: 4 },
          chronicle: "天子追赠战殁者，并定军务旬奏之制，司空府颇有不满。",
        },
        {
          label: "仅发常诏，不涉军务",
          hint: "风险最低，政治机会被放弃。",
          effects: { security: 2, prestige: -2, caoAlert: -1 },
          relations: { cao_cao: 1 },
          chronicle: "朝廷只依常制发诏，未趁宛城之变干预军务。",
        },
      ],
    },
    {
      id: "imperial_clan",
      fixedTurn: 15,
      title: "宗亲之表",
      category: "宗室",
      text:
        "刘表遣使奉表，称愿修宗庙、贡方物，并请朝廷确认荆州官属。有人主张借宗亲之名建立南方退路，也有人担心刺激曹操。",
      choices: [
        {
          label: "厚答宗亲，约为外援",
          hint: "外部平衡明显增加。",
          effects: { prestige: 5, caoAlert: 9, security: -2 },
          hidden: { externalBalance: 11, escapeRoute: 8 },
          relations: { liu_biao: 13, cao_cao: -4 },
          chronicle: "天子厚答刘表，荆州与汉廷往来渐密。",
        },
        {
          label: "依礼答复，不作私约",
          hint: "稳妥维持宗亲关系。",
          effects: { prestige: 4, authority: 1 },
          relations: { liu_biao: 5, xun_yu: 2 },
          chronicle: "朝廷依礼答复荆州宗亲，未作越制私约。",
        },
        {
          label: "令其先输粮助朝",
          hint: "增加国库，但可能显得朝廷困窘。",
          effects: { treasury: 9, prestige: -3, caoAlert: 2 },
          relations: { liu_biao: -3, cao_cao: 2 },
          chronicle: "天子令荆州输粮助朝，许都得实惠，天下亦知汉廷财困。",
        },
      ],
    },
    {
      id: "corruption_case",
      fixedTurn: 17,
      title: "赈粮侵吞案",
      category: "民政",
      text:
        "御史发现许都周边赈粮层层克扣，涉案者既有旧臣亲族，也有司空府属吏。若彻查，可能同时得罪两派；若压案，民怨会迅速累积。",
      choices: [
        {
          label: "不分派系，公开彻查",
          hint: "威望与皇权上升，安全和官员支持承压。",
          effects: { prestige: 9, authority: 7, officials: -5, security: -4, caoAlert: 5 },
          hidden: { peopleStability: 9 },
          relations: { yang_biao: 2, xun_yu: 3, cao_cao: -2 },
          chronicle: "天子命御史不避权门，公开彻查赈粮侵吞案。",
        },
        {
          label: "由荀彧内部整顿",
          hint: "较稳定，但皇帝存在感较弱。",
          effects: { prestige: 4, officials: 4, security: 2, caoAlert: -1 },
          hidden: { peopleStability: 5 },
          relations: { xun_yu: 7, cao_cao: 2 },
          chronicle: "赈粮案交尚书令内部整顿，多名小吏获罪，权门未受深究。",
        },
        {
          label: "暂压其案，先保朝局",
          hint: "短期安全，长期民怨。",
          effects: { security: 5, prestige: -8, officials: -2, caoAlert: -3 },
          hidden: { peopleStability: -10 },
          chronicle: "朝廷暂压赈粮案，许都权门得以自保，民间怨声渐起。",
        },
      ],
    },
    {
      id: "dong_cheng_plan",
      fixedTurn: 19,
      title: "董承夜议",
      category: "密谋",
      text:
        "董承请求夜入宫中，称已有数名将领与旧臣愿奉密诏。他建议趁曹操外出时夺取宫门与尚书台。伏皇后担忧时机尚未成熟。",
      choices: [
        {
          label: "准其筹备，不定日期",
          hint: "忠汉网络大增，泄密与警戒同步上升。",
          effects: { authority: 3, security: -5, caoAlert: 12 },
          hidden: { loyalNetwork: 16, leakRisk: 14 },
          relations: { dong_cheng: 12, empress_fu: -2, cao_cao: -7 },
          chronicle: "天子准董承暗中筹备，未授举事日期。许都暗流骤急。",
        },
        {
          label: "令其停止，先固宫禁",
          hint: "降低泄密风险，忠臣可能失望。",
          effects: { security: 8, caoAlert: -6, authority: -2 },
          hidden: { loyalNetwork: -7, leakRisk: -10 },
          relations: { dong_cheng: -8, empress_fu: 5, xun_yu: 2 },
          chronicle: "天子令董承停止冒进，先固宫禁与百官人心。",
        },
        {
          label: "转为联络河北与荆州",
          hint: "以外部制衡替代宫变。",
          effects: { prestige: 3, caoAlert: 8, security: -3 },
          hidden: { externalBalance: 12, loyalNetwork: 5, leakRisk: 7 },
          relations: { yuan_shao: 5, liu_biao: 5, dong_cheng: 3 },
          chronicle: "密谋改为外联河北、荆州，不急于在许都举事。",
        },
      ],
    },
    {
      id: "court_debate",
      fixedTurn: 21,
      title: "朝会之争",
      category: "朝政",
      text:
        "百官争论：地方军阀互相攻伐，朝廷应继续频繁授官以换取名义臣服，还是收紧官爵以保制度尊严。",
      choices: [
        {
          label: "广授官爵，先聚天下名义",
          hint: "短期威望和外部平衡上升，皇权含金量下降。",
          effects: { prestige: 6, authority: -4, officials: 2, caoAlert: 3 },
          hidden: { externalBalance: 7 },
          chronicle: "朝廷广授诸侯官爵，天下多奉汉号，官爵亦渐轻。",
        },
        {
          label: "收紧官爵，违制者不授",
          hint: "皇权制度性增强，但诸侯关系恶化。",
          effects: { authority: 8, prestige: -2, officials: 3, caoAlert: 4 },
          relations: { yuan_shao: -4, sun_ce: -3, liu_biao: -2 },
          chronicle: "天子收紧官爵，欲重建朝廷制度威严。",
        },
        {
          label: "设考功条件，分级授予",
          hint: "均衡、稳健。",
          effects: { authority: 4, prestige: 3, officials: 5, treasury: -2 },
          chronicle: "朝廷定诸侯贡赋、讨逆与安民之考功条件，分级授官。",
        },
      ],
    },
    {
      id: "final_pressure",
      fixedTurn: 23,
      title: "司空府试探",
      category: "终局",
      text:
        "司空府奏请扩大录尚书事权限，并要求宫中所有密使名籍备案。曹操称天下将有大战，必须政令一出。你的二十四个月布局即将接受考验。",
      choices: [
        {
          label: "拒绝，并召集百官廷议",
          hint: "高风险检验皇权与支持。",
          effects: { authority: 10, officials: 5, security: -8, caoAlert: 14 },
          chronicle: "天子拒绝扩大录尚书事权限，召百官公开廷议。",
        },
        {
          label: "同意军务集中，保留宫中名籍",
          hint: "折中守住底线。",
          effects: { authority: 2, security: 5, caoAlert: 2, officials: 2 },
          chronicle: "天子同意军务集中，但拒交宫中密使与内侍名籍。",
        },
        {
          label: "全数准奏，以待后机",
          hint: "安全上升，皇权大幅下降。",
          effects: { security: 10, caoAlert: -10, authority: -10, prestige: -3 },
          chronicle: "天子全准司空府所请，许都政令归一，汉廷自主更微。",
        },
      ],
    },
  ],

  causalEvents: [
    {
      id: "causal_grain_and_army",
      title: "度支与军粮",
      category: "因果奏报",
      text: "尚书台将国库簿册与前线粮册并陈御前：朝廷的钱粮已经无法同时满足百官俸给、宫禁修缮与军团转运。此前的征调和行军，如今必须有人承担代价。",
      choices: [
        {
          label: "先足军粮，缓发俸给",
          hint: "军团补给改善，百官支持下降。",
          effects: { treasury: -4, officials: -4, security: 2 },
          causalLinks: { army: { owners: ["court"], supply: 10, morale: 2 }, factions: { loyalists: { support: -3, tension: 3 } } },
          chronicle: "天子命度支先足军粮，百官俸给暂缓，前线得以续行。",
        },
        {
          label: "裁减军运，保全朝廷",
          hint: "国库喘息，军团士气与补给受损。",
          effects: { treasury: 4, officials: 2, prestige: -2 },
          causalLinks: { army: { owners: ["court"], supply: -7, morale: -4 }, factions: { gentry: { support: 2, tension: -1 } } },
          chronicle: "朝廷裁减军运以保俸给，前线将士因粮道收紧而怨。",
        },
        {
          label: "令州郡按地分担",
          hint: "取得有限钱粮，但地方压力和民怨上升。",
          effects: { treasury: 6, authority: 2, prestige: -2 },
          hidden: { peopleStability: -5 },
          causalLinks: { strategy: { courtCities: { supply: -6, courtLoyalty: -3, pressure: 3 } }, factions: { gentry: { support: -4, tension: 5 } } },
          chronicle: "天子令受朝命州郡按地分担军需，度支稍充，地方怨声亦起。",
        },
      ],
    },
    {
      id: "causal_war_aftermath",
      title: "战殁名籍",
      category: "因果奏报",
      text: "军报不再只有胜负。阵亡者名籍、伤兵安置、功臣请赏与沿途流民一并送到御前。战场上的每一次推进，都在朝堂留下新的债。",
      choices: [
        {
          label: "发帑抚恤，先安军民",
          hint: "花费国库，修复民心并鼓舞军队。",
          effects: { treasury: -6, prestige: 5, officials: 2 },
          hidden: { peopleStability: 6 },
          causalLinks: { army: { owners: ["court"], morale: 6, loyalty: 3, fatigue: -2 }, factions: { imperial: { support: 3, tension: -2 } } },
          chronicle: "朝廷发帑抚恤阵亡与流离之家，军民稍知战事并非无人过问。",
        },
        {
          label: "明诏论功，重奖主将",
          hint: "强化权威与军心，也会提高曹氏警戒。",
          effects: { authority: 4, prestige: 3, treasury: -3, caoAlert: 4 },
          causalLinks: { army: { owners: ["court"], morale: 4, loyalty: 6 }, factions: { cao: { support: -1, tension: 4 } } },
          chronicle: "天子明诏论功，军中知赏罚出于汉廷，司空府亦更加留意。",
        },
        {
          label: "只录战果，暂缓追恤",
          hint: "节省开支，但民心和军心持续受损。",
          effects: { treasury: 2, prestige: -4, officials: -2 },
          hidden: { peopleStability: -4 },
          causalLinks: { army: { owners: ["court"], morale: -5, loyalty: -2 }, factions: { loyalists: { support: -3, tension: 4 } } },
          chronicle: "朝廷只录战果而缓追恤，簿册虽简，军民怨意未消。",
        },
      ],
    },
    {
      id: "causal_faction_deadlock",
      title: "尚书台封驳",
      category: "因果奏报",
      text: "数道诏令在尚书台与司空府之间往返，帝后近臣、汉室旧臣和曹氏幕府各执一词。此前累积的猜疑已经开始拖慢政令执行。",
      choices: [
        {
          label: "召五方廷议，当面定责",
          hint: "缓和多数派系，但会消耗皇权威势。",
          effects: { officials: 4, authority: -2, security: 2 },
          causalLinks: { factions: { imperial: { tension: -4 }, loyalists: { tension: -4 }, cao: { tension: -3 }, regional: { tension: -2 }, gentry: { tension: -3 } } },
          chronicle: "天子召各方廷议，责令当面陈说，尚书台封驳之争暂解。",
        },
        {
          label: "御笔独断，限期奉行",
          hint: "皇权上升，反对派系张力加剧。",
          effects: { authority: 6, officials: -3, caoAlert: 4 },
          causalLinks: { factions: { imperial: { support: 4 }, loyalists: { tension: 3 }, cao: { tension: 6 }, gentry: { tension: 3 } } },
          chronicle: "天子御笔独断，命尚书台限期奉行，朝令得出而异议更深。",
        },
        {
          label: "委荀彧调停，换取执行",
          hint: "提高执行稳定，曹氏影响有所加深。",
          effects: { officials: 3, security: 3, authority: -2, caoAlert: -2 },
          relations: { xun_yu: 5 },
          causalLinks: { factions: { cao: { support: 5, tension: -5 }, loyalists: { support: -2, tension: 2 } } },
          chronicle: "天子委荀彧调停台府之争，政令复行，汉臣亦忧外府权重。",
        },
      ],
    },
    {
      id: "causal_refugees",
      title: "道旁流民",
      category: "因果奏报",
      text: "战线与征调经过的州郡出现流民，驿路、城门和官仓同时承压。若只把他们当作地图上的数字，盗贼、疫病与谣言很快会抵达许都。",
      choices: [
        {
          label: "沿军路设粥棚与医舍",
          hint: "消耗国库，明显恢复民稳与道路补给。",
          effects: { treasury: -5, prestige: 4, security: 2 },
          hidden: { peopleStability: 8 },
          causalLinks: { strategy: { strainedRoutes: { supply: 5, pressure: -5 } }, factions: { gentry: { support: 3, tension: -3 } } },
          chronicle: "朝廷沿军路设粥棚医舍，流民得食，驿道压力稍减。",
        },
        {
          label: "迁入新附城池屯田",
          hint: "改善城池供给，但短期地方张力上升。",
          effects: { authority: 2, treasury: -2 },
          hidden: { peopleStability: 3 },
          causalLinks: { strategy: { courtCities: { supply: 5, courtLoyalty: -2, pressure: 2 } }, factions: { gentry: { tension: 3 } } },
          chronicle: "天子命流民迁入新附州郡屯田，来年或有收成，眼下仍需安置。",
        },
        {
          label: "封闭宫城，交州郡自理",
          hint: "保全国库和宫禁，民心与威望下降。",
          effects: { treasury: 2, security: 3, prestige: -5 },
          hidden: { peopleStability: -7 },
          causalLinks: { factions: { imperial: { support: -2 }, gentry: { support: -4, tension: 5 } } },
          chronicle: "宫城闭门，流民交州郡自理，许都暂静而道路哭声不绝。",
        },
      ],
    },
    {
      id: "causal_personal_appeal",
      title: "旧臣求见",
      category: "因果奏报",
      text: "一名曾受诏令牵连的旧臣请求单独入见。他没有重述大道理，只将过去数月的取舍逐件列出，询问天子是否还记得当时的承诺。",
      choices: [
        {
          label: "留中长谈，承认旧憾",
          hint: "修复关键关系与百官支持。",
          effects: { officials: 4, authority: -1 },
          relations: { dong_cheng: 4, yang_biao: 4, empress_fu: 2 },
          causalLinks: { factions: { loyalists: { support: 4, tension: -4 }, imperial: { support: 2, tension: -2 } } },
          chronicle: "天子留旧臣长谈，坦言数月间不得已之处，君臣旧隙稍解。",
        },
        {
          label: "以新官相授，责其办事",
          hint: "强化皇权并换取执行，但增加国库支出。",
          effects: { authority: 4, treasury: -3, officials: 2 },
          relations: { yang_biao: 3, xun_yu: 2 },
          causalLinks: { factions: { loyalists: { support: 3 }, gentry: { support: 2 } } },
          chronicle: "天子以新官授旧臣，命其以实绩回答朝局，而非空论忠义。",
        },
        {
          label: "不许私见，只令上奏",
          hint: "维护制度距离，人物芥蒂继续累积。",
          effects: { authority: 2, officials: -3 },
          relations: { dong_cheng: -3, yang_biao: -3 },
          causalLinks: { factions: { loyalists: { support: -4, tension: 5 } } },
          chronicle: "天子不许私见，只令循制上奏，旧臣退下而心结未解。",
        },
      ],
    },
    {
      id: "causal_new_territory",
      title: "新附州郡",
      category: "因果奏报",
      text: "新近奉汉廷号令的城池送来户籍、仓簿与官员名册。城池易帜只是开始：征税、驻军、安民与任官将决定它究竟是朝廷根基，还是下一场叛乱。",
      choices: [
        {
          label: "三月薄税，先复民业",
          hint: "短期少收钱粮，提升民稳与城池忠诚。",
          effects: { treasury: -3, prestige: 4 },
          hidden: { peopleStability: 5 },
          causalLinks: { strategy: { courtCities: { courtLoyalty: 7, supply: 3, pressure: -4 } }, factions: { gentry: { support: 3, tension: -2 } } },
          chronicle: "新附州郡三月薄税，先复田业，汉廷名义渐由旗号落到民生。",
        },
        {
          label: "核户征赋，充实度支",
          hint: "国库收益较高，地方压力上升。",
          effects: { treasury: 8, authority: 2, prestige: -2 },
          hidden: { peopleStability: -4 },
          causalLinks: { strategy: { courtCities: { supply: -3, courtLoyalty: -4, pressure: 5 } }, factions: { gentry: { support: -3, tension: 4 } } },
          chronicle: "朝廷核定新附户籍并征赋，度支得补，地方负担亦随之而来。",
        },
        {
          label: "遣亲信监郡，整军设防",
          hint: "提高城防和皇权，消耗国库并刺激曹氏。",
          effects: { treasury: -5, authority: 5, caoAlert: 4 },
          causalLinks: { strategy: { courtCities: { defense: 7, courtLoyalty: 4 } }, army: { owners: ["court"], loyalty: 3, supply: 2 } },
          chronicle: "天子遣亲信监郡整军，新附之地渐有汉廷直接号令。",
        },
      ],
    },
  ],

  pathEvents: [
    {
      id: "path_benevolent_granaries", pathId: "benevolent", pathStage: 1, title: "仓廪先问何人", category: "帝业·仁政",
      text: "连月安民之后，尚书台请定常平仓次序：灾户、军属与官吏皆称自己最急。一次赈济容易，能否留下成法才是考验。",
      choices: [
        { label: "灾户为先，按户给粮", hint: "民稳与威望提高，国库承压。", effects: { treasury: -5, prestige: 3 }, hidden: { peopleStability: 6 }, relations: { xun_yu: 2 }, chronicle: "朝廷定常平仓以灾户为先，按籍给粮。" },
        { label: "军民各半，先保转运", hint: "兼顾宫禁与民生。", effects: { treasury: -3, security: 2, prestige: 1 }, hidden: { peopleStability: 3 }, chronicle: "常平仓分济军民，先保要道不乱。" },
        { label: "交由州郡因地施行", hint: "节省国库，但执行不一。", effects: { treasury: 1, officials: -1 }, hidden: { peopleStability: 1 }, chronicle: "朝廷命州郡自定赈次，各地施行不一。" },
      ],
    },
    {
      id: "path_benevolent_magistrates", pathId: "benevolent", pathStage: 2, title: "循吏之选", category: "帝业·仁政",
      text: "数郡请求补任守令。名望、才能与地方人情难以兼得，群臣争论怎样的人才配得上所谓仁政。",
      choices: [
        { label: "察绩擢用能吏", hint: "百官与皇权提高。", effects: { officials: 5, authority: 3, caoAlert: 2 }, relations: { yang_biao: 2 }, chronicle: "朝廷察绩擢守令，责其以实政安民。" },
        { label: "听百姓与乡议共举", hint: "民稳显著提高，中央权力稍退。", effects: { authority: -1, prestige: 3 }, hidden: { peopleStability: 5 }, chronicle: "朝廷许郡中乡议举守令，民间称便。" },
        { label: "请司空府统一铨选", hint: "执行稳妥，曹氏警戒下降。", effects: { officials: 2, security: 2, caoAlert: -3, authority: -2 }, chronicle: "守令铨选多归司空府，地方政务迅速补齐。" },
      ],
    },
    {
      id: "path_restoration_seals", pathId: "restoration", pathStage: 1, title: "印绶归台", category: "帝业·归政",
      text: "战乱以来，各署印绶、文簿与任命多由权府代行。若要重建中枢，首先必须决定哪些权柄应回到尚书台。",
      choices: [
        { label: "先收文官铨选与考课", hint: "皇权、百官提高，警戒上升。", effects: { authority: 5, officials: 4, caoAlert: 5 }, relations: { yang_biao: 3 }, chronicle: "天子诏收文官铨选与考课于尚书台。" },
        { label: "只统一诏令格式与档案", hint: "温和恢复制度。", effects: { authority: 3, officials: 2, caoAlert: 1, treasury: -1 }, chronicle: "朝廷先统一诏令与档案，中枢法度稍复。" },
        { label: "暂不争权，先清积案", hint: "百官支持提高，皇权进展较慢。", effects: { officials: 5, authority: 1, caoAlert: -1 }, chronicle: "尚书台先清积案，不急于争夺印绶。" },
      ],
    },
    {
      id: "path_restoration_offices", pathId: "restoration", pathStage: 2, title: "百司复位", category: "帝业·归政",
      text: "尚书台渐能办事，各署却仍职责重叠。重定百司意味着真正触动既有权力，也可能让汉廷第一次拥有稳定执行力。",
      choices: [
        { label: "依旧制重分百司", hint: "制度收益高，国库与警戒承压。", effects: { authority: 5, officials: 5, treasury: -4, caoAlert: 4 }, chronicle: "朝廷依汉制重分百司，政令归于有司。" },
        { label: "保留权府差遣，增设复核", hint: "折中提升执行与安全。", effects: { authority: 2, officials: 3, security: 2, caoAlert: 1 }, chronicle: "百司增设复核，权府差遣仍暂保留。" },
        { label: "以人物信用代替改制", hint: "改善关键关系，制度进展有限。", effects: { officials: 2 }, relations: { xun_yu: 4, yang_biao: 3 }, chronicle: "天子托付重臣分掌积务，暂缓全面改制。" },
      ],
    },
    {
      id: "path_martial_commission", pathId: "martial", pathStage: 1, title: "奉诏出师", category: "帝业·戎马",
      text: "前线诸军都愿借天子名义，却未必愿受同一道军令。若以战功中兴，第一步便是让胜利真正记在朝廷名下。",
      choices: [
        { label: "颁统一节钺与军令", hint: "皇权与威望提高，警戒明显上升。", effects: { authority: 5, prestige: 4, treasury: -2, caoAlert: 6 }, chronicle: "天子颁节钺统一军令，诸军皆称奉诏。" },
        { label: "只定共同讨逆名义", hint: "稳妥提高威望与外部制衡。", effects: { prestige: 4, caoAlert: 2 }, hidden: { externalBalance: 3 }, chronicle: "朝廷诏诸军共奉讨逆名义，不强夺其兵柄。" },
        { label: "以厚赏换取一役听命", hint: "国库换取短期军令。", effects: { treasury: -5, authority: 3, security: 2 }, chronicle: "天子厚赏诸军，换得一役奉诏而行。" },
      ],
    },
    {
      id: "path_martial_veterans", pathId: "martial", pathStage: 2, title: "归来将士", category: "帝业·戎马",
      text: "一批久战将士回到朝廷控制区。他们既是可用之兵，也是需要田宅、抚恤与归属的人。如何安置将决定戎马中兴是否只剩下一场胜仗。",
      choices: [
        { label: "授田屯守新附城池", hint: "国库下降，宫禁与民稳提高。", effects: { treasury: -4, security: 3 }, hidden: { peopleStability: 3 }, chronicle: "朝廷授田安置归来将士，使之屯守新附。" },
        { label: "择精锐编入宿卫", hint: "宫禁大幅提高，曹氏警戒上升。", effects: { security: 6, authority: 2, caoAlert: 5, treasury: -2 }, chronicle: "归来精锐被选入宿卫，宫门声势一新。" },
        { label: "遣归乡里，减免赋役", hint: "民稳与威望提高，军事收益较少。", effects: { prestige: 3 }, hidden: { peopleStability: 5 }, chronicle: "朝廷遣老卒归乡并减免赋役，州里称颂。" },
      ],
    },
  ],

  randomEvents: [
    {
      id: "grain_price",
      title: "许都粮价",
      category: "民生",
      text: "连日阴雨，许都粮价上涨，百官俸粮亦被拖欠。商贾请求允许自由运粮，旧臣则要求平价征购。",
      choices: [
        {
          label: "开放商运并减关税",
          hint: "国库略减，民间稳定提高。",
          effects: { treasury: -3, prestige: 4 },
          hidden: { peopleStability: 6 },
          chronicle: "朝廷开放商运、减免关税，许都粮价稍平。",
        },
        {
          label: "按官价征粮",
          hint: "国库增加，但民间不满。",
          effects: { treasury: 6, prestige: -4, officials: 2 },
          hidden: { peopleStability: -6 },
          chronicle: "朝廷按官价征粮，官仓渐充，商民多有怨言。",
        },
        {
          label: "请司空府调军粮赈济",
          hint: "安全和民心改善，曹氏影响加深。",
          effects: { prestige: 3, security: 3, authority: -2, caoAlert: -3 },
          relations: { cao_cao: 3 },
          chronicle: "司空府拨军粮入市，许都暂安，百姓多称曹氏之惠。",
        },
      ],
    },
    {
      id: "forged_edict",
      title: "疑似伪诏",
      category: "制度",
      text: "地方传回一封以朝廷名义任命县令的诏书，印迹与格式均有可疑。若处置不当，天下将更轻视玺书。",
      choices: [
        {
          label: "公开验诏并惩处",
          hint: "皇权上升，花费行政资源。",
          effects: { authority: 6, prestige: 3, treasury: -2, officials: -1 },
          chronicle: "朝廷公开验诏，查出伪造者并明示天下。",
        },
        {
          label: "秘密撤换，避免扩散",
          hint: "安全稳妥，制度收益有限。",
          effects: { security: 3, authority: 1 },
          chronicle: "伪诏案被秘密处置，未使流言广布。",
        },
        {
          label: "交司空府查办",
          hint: "降低警戒，但削弱玺书独立。",
          effects: { caoAlert: -4, security: 4, authority: -3 },
          relations: { cao_cao: 2 },
          chronicle: "疑似伪诏交司空府查办，地方更畏曹氏法令。",
        },
      ],
    },
    {
      id: "old_official_petition",
      title: "老臣请退",
      category: "百官",
      text: "一名随驾东归的老臣以病请退，称在许都难以自处。若准其离去，旧臣可能纷纷效仿。",
      choices: [
        {
          label: "亲笔慰留",
          hint: "提升百官支持。",
          effects: { officials: 6, authority: 2, treasury: -1 },
          chronicle: "天子亲笔慰留老臣，百官感念。",
        },
        {
          label: "准退并加赐",
          hint: "保全体面，消耗国库。",
          effects: { prestige: 3, treasury: -4, officials: 1 },
          chronicle: "天子准老臣致仕，加赐钱帛以全其节。",
        },
        {
          label: "不准，命其继续供职",
          hint: "强调法度，但支持下降。",
          effects: { authority: 3, officials: -4 },
          chronicle: "朝廷不准老臣请退，命其继续供职。",
        },
      ],
    },
    {
      id: "palace_rumor",
      title: "宫中流言",
      category: "宫禁",
      text: "宫中流传天子将秘密出奔荆州的说法。真假难辨，司空府已开始询问内侍。",
      choices: [
        {
          label: "彻查流言源头",
          hint: "降低泄密，但可能伤害宫人信任。",
          effects: { security: 4, officials: -2, caoAlert: 2 },
          hidden: { leakRisk: -7 },
          chronicle: "宫中彻查出奔流言，多名内侍被调离。",
        },
        {
          label: "公开斥为妄言",
          hint: "威望与安全小幅改善。",
          effects: { prestige: 2, security: 2, authority: 1 },
          chronicle: "天子公开斥出奔之说为妄言，流言暂息。",
        },
        {
          label: "借流言试探荆州反应",
          hint: "增加退路，也提高警戒。",
          effects: { caoAlert: 6, security: -2 },
          hidden: { escapeRoute: 7, leakRisk: 4 },
          relations: { liu_biao: 4 },
          chronicle: "宫中暗借流言试探荆州，南方退路稍有眉目。",
        },
      ],
    },
    {
      id: "tax_petition",
      title: "郡县减赋表",
      category: "民政",
      text: "颍川数县因流民与兵役请求减赋。司空府担心军粮不足，地方士族则称再征必乱。",
      choices: [
        {
          label: "减赋半年",
          hint: "民心与威望上升，国库下降。",
          effects: { prestige: 5, treasury: -6, officials: 2 },
          hidden: { peopleStability: 7 },
          chronicle: "颍川数县获准减赋半年，流民稍安。",
        },
        {
          label: "只减灾户",
          hint: "折中方案。",
          effects: { prestige: 3, treasury: -3, officials: 2 },
          hidden: { peopleStability: 4 },
          chronicle: "朝廷只减免受灾户赋役，地方勉强接受。",
        },
        {
          label: "军兴为重，不准减赋",
          hint: "国库增加，民间稳定下降。",
          effects: { treasury: 5, prestige: -5, security: -1 },
          hidden: { peopleStability: -8 },
          chronicle: "朝廷以军兴为重拒绝减赋，颍川民怨加深。",
        },
      ],
    },
    {
      id: "scholar_recommendation",
      title: "征辟名士",
      category: "人才",
      text: "荀彧荐举数名颍川士人入尚书台。旧臣担心新官尽出曹氏门下，但朝廷确实缺少能吏。",
      choices: [
        {
          label: "全部征辟，以才为先",
          hint: "官僚效率提高，曹氏关系改善。",
          effects: { officials: 7, authority: 2, caoAlert: -3 },
          relations: { xun_yu: 6, cao_cao: 2, yang_biao: -2 },
          chronicle: "朝廷征辟颍川士人，尚书台办事渐捷。",
        },
        {
          label: "新旧各半，保持平衡",
          hint: "均衡提升。",
          effects: { officials: 5, authority: 3, treasury: -2 },
          relations: { xun_yu: 3, yang_biao: 3 },
          chronicle: "朝廷新旧并用，尚书台暂得平衡。",
        },
        {
          label: "暂缓征辟，防止结党",
          hint: "警戒略降，百官效率受损。",
          effects: { caoAlert: -2, officials: -5, authority: 1 },
          relations: { xun_yu: -5, yang_biao: 2 },
          chronicle: "天子暂缓征辟，尚书台缺员之困未解。",
        },
      ],
    },
    {
      id: "seal_ceremony",
      title: "宗庙告祭",
      category: "礼制",
      text: "太常请修宗庙告祭，以宣示汉统未绝。所费不小，且许都宫室尚未完备。",
      choices: [
        {
          label: "隆重举行",
          hint: "威望大增，国库消耗。",
          effects: { prestige: 8, authority: 4, treasury: -7, caoAlert: 2 },
          chronicle: "许都举行宗庙告祭，汉家礼乐一时复振。",
        },
        {
          label: "从简告祭",
          hint: "稳妥小幅提升。",
          effects: { prestige: 4, authority: 2, treasury: -2 },
          chronicle: "宗庙告祭从简举行，百官仍见汉统之存。",
        },
        {
          label: "暂缓，先济饥民",
          hint: "民间威望上升，礼官不满。",
          effects: { prestige: 3, treasury: -3, officials: -2 },
          hidden: { peopleStability: 5 },
          chronicle: "天子暂缓大礼，将所费转济饥民。",
        },
      ],
    },
    {
      id: "cao_gift",
      title: "司空献礼",
      category: "关系",
      text: "曹操献上战马、绢帛与粮食，请求赐宴。接受可解国库之困，但过度亲近会使忠臣失望。",
      choices: [
        {
          label: "受礼并赐宴",
          hint: "国库、安全和关系改善。",
          effects: { treasury: 8, security: 3, caoAlert: -6, authority: -2 },
          relations: { cao_cao: 7, dong_cheng: -3 },
          chronicle: "天子受司空献礼并赐宴，许都君臣表面融洽。",
        },
        {
          label: "受粮而退珍玩",
          hint: "兼顾实用与名节。",
          effects: { treasury: 5, prestige: 3, caoAlert: -1 },
          relations: { cao_cao: 2, yang_biao: 2 },
          chronicle: "天子受军粮而退珍玩，朝野称其节俭。",
        },
        {
          label: "全部辞退",
          hint: "威望与皇权提高，关系恶化。",
          effects: { prestige: 5, authority: 3, caoAlert: 6, treasury: -2 },
          relations: { cao_cao: -5, dong_cheng: 3 },
          chronicle: "天子辞退司空所献，旧臣称颂，司空府多有猜疑。",
        },
      ],
    },
    {
      id: "border_bandits",
      title: "近郡盗贼",
      category: "治安",
      text: "许都近郡盗贼聚众，地方请求发兵。朝廷没有直属军队，只能依赖曹军或募集地方义勇。",
      choices: [
        {
          label: "诏曹军讨捕",
          hint: "安全提高，皇权依赖加深。",
          effects: { security: 6, caoAlert: -3, authority: -2 },
          relations: { cao_cao: 3 },
          chronicle: "朝廷诏曹军讨捕近郡盗贼，道路稍安。",
        },
        {
          label: "允许地方募义勇",
          hint: "增强地方自主，存在失控风险。",
          effects: { security: 2, authority: 2, prestige: 2, caoAlert: 4 },
          hidden: { externalBalance: 3 },
          chronicle: "朝廷许地方募集义勇，盗贼受制，地方武装亦渐增长。",
        },
        {
          label: "以赦令招抚",
          hint: "国库消耗少，结果不稳定。",
          effects: { prestige: 3, security: -1, treasury: -1 },
          hidden: { peopleStability: 3 },
          chronicle: "天子下赦招抚盗众，部分归降，余众散入山泽。",
        },
      ],
    },
    {
      id: "imperial_tutor",
      title: "讲经之议",
      category: "宫廷",
      text: "伏皇后建议恢复经筵，定期召儒臣讲经议政。此举可让你公开接触百官，但司空府希望派人旁听。",
      choices: [
        {
          label: "恢复经筵，不许外府旁听",
          hint: "皇权和百官支持上升，警戒增加。",
          effects: { authority: 5, officials: 5, caoAlert: 6, treasury: -2 },
          relations: { empress_fu: 4, yang_biao: 3 },
          chronicle: "天子恢复经筵，不许外府官员旁听。",
        },
        {
          label: "恢复经筵，准荀彧旁听",
          hint: "稳妥增加接触渠道。",
          effects: { authority: 3, officials: 5, caoAlert: -1, treasury: -2 },
          relations: { xun_yu: 5, empress_fu: 2 },
          chronicle: "经筵恢复，荀彧亦列席，百官议政渐有常制。",
        },
        {
          label: "暂不恢复",
          hint: "节省资源，但错失政治空间。",
          effects: { treasury: 2, officials: -3 },
          chronicle: "经筵之议被暂缓，宫中仍少公开议政之机。",
        },
      ],
    },
    {
      id: "envoy_jiangdong",
      title: "江东求封",
      category: "外交",
      text: "孙策遣使求取更高官号，愿以讨袁术、定江东为功。其势力虽远，却可能成为朝廷新的筹码。",
      choices: [
        {
          label: "加封并要求奉贡",
          hint: "外部平衡与国库增长，曹氏警戒上升。",
          effects: { prestige: 4, treasury: 3, caoAlert: 5 },
          hidden: { externalBalance: 6 },
          relations: { sun_ce: 9, yuan_shu: -4 },
          chronicle: "朝廷加封孙策并令其奉贡，江东声势日盛。",
        },
        {
          label: "只确认现有官号",
          hint: "温和维持关系。",
          effects: { prestige: 2, authority: 1 },
          relations: { sun_ce: 3 },
          chronicle: "朝廷确认孙策现有官号，未作更高封授。",
        },
        {
          label: "拒绝，称其功未足",
          hint: "维护官爵尊严，江东关系恶化。",
          effects: { authority: 4, prestige: -1 },
          relations: { sun_ce: -8, yang_biao: 2 },
          chronicle: "天子以功未足拒绝孙策加封之请。",
        },
      ],
    },
    {
      id: "court_banquet",
      title: "岁时赐宴",
      category: "人心",
      text: "岁时将至，百官俸禄不足。是否举行赐宴与赏赐，成为观察朝廷财力和君臣关系的风向。",
      choices: [
        {
          label: "赐宴并赏百官",
          hint: "支持大增，国库明显下降。",
          effects: { officials: 8, prestige: 3, treasury: -8 },
          chronicle: "天子赐宴百官，虽物资简薄，朝臣多有感念。",
        },
        {
          label: "从简赐宴",
          hint: "小幅改善支持。",
          effects: { officials: 4, treasury: -3, prestige: 1 },
          chronicle: "朝廷从简赐宴，君臣共度岁时。",
        },
        {
          label: "停宴以节财",
          hint: "节省国库，百官失望。",
          effects: { treasury: 4, officials: -5 },
          chronicle: "天子停岁时赐宴以节财，百官私议朝廷困窘。",
        },
      ],
    },
    {
      id: "secret_letter",
      title: "无名密书",
      category: "谍报",
      text: "宫门发现一封无名密书，称司空府内有人愿为天子通报军情。信中要求以官爵为报。",
      choices: [
        {
          label: "试探接触",
          hint: "可能扩展密线，也可能是诱饵。",
          effects: { caoAlert: 5, security: -3 },
          hidden: { loyalNetwork: 7, leakRisk: 8 },
          chronicle: "宫中派人试探无名密书所指之人，真假尚未明朗。",
        },
        {
          label: "交董承查验",
          hint: "忠汉网络增加，董承关系改善。",
          effects: { security: -1, caoAlert: 4 },
          hidden: { loyalNetwork: 5, leakRisk: 5 },
          relations: { dong_cheng: 5 },
          chronicle: "无名密书交董承暗查，宫中耳目稍增。",
        },
        {
          label: "焚毁，不予回应",
          hint: "最安全，但失去机会。",
          effects: { security: 4, caoAlert: -2 },
          hidden: { leakRisk: -4 },
          chronicle: "天子焚毁无名密书，不使宫中卷入未知圈套。",
        },
      ],
    },
    {
      id: "imperial_clothing",
      title: "礼服残缺",
      category: "礼制",
      text: "大朝会所用礼服、冠冕多在战乱中散失。太常请求重制，费用可抵数月宫中开支。",
      choices: [
        {
          label: "依制重制",
          hint: "礼制威望提升，国库下降。",
          effects: { prestige: 6, authority: 3, treasury: -6 },
          chronicle: "朝廷依制重制冠冕礼服，汉家仪容稍复。",
        },
        {
          label: "修补旧服",
          hint: "节俭而体面。",
          effects: { prestige: 3, treasury: -2, officials: 1 },
          chronicle: "太常修补旧服，大朝会得以如期举行。",
        },
        {
          label: "停大朝会",
          hint: "节省国库，但皇权存在感下降。",
          effects: { treasury: 3, authority: -4, prestige: -2 },
          chronicle: "因礼服残缺，朝廷停大朝会一次。",
        },
      ],
    },
    {
      id: "frontier_victory",
      title: "捷报入朝",
      category: "军事",
      text: "曹军传来捷报，请朝廷明诏嘉奖并授官。如何表述战功，将影响天下对胜利归属的认知。",
      choices: [
        {
          label: "称奉诏讨逆，重申朝廷名义",
          hint: "威望与皇权提高，警戒增加。",
          effects: { prestige: 6, authority: 5, caoAlert: 6 },
          relations: { cao_cao: -2, yang_biao: 3 },
          chronicle: "朝廷诏称诸军奉天子命讨逆，天下皆闻汉廷之名。",
        },
        {
          label: "厚奖将士，不争功名",
          hint: "改善曹氏关系。",
          effects: { security: 3, treasury: -3, caoAlert: -4 },
          relations: { cao_cao: 5 },
          chronicle: "天子厚奖将士，不与司空府争论战功归属。",
        },
        {
          label: "只赏基层军士",
          hint: "军心与威望小幅提升，曹氏略有不悦。",
          effects: { prestige: 3, treasury: -4, authority: 2, caoAlert: 2 },
          relations: { cao_cao: -1 },
          chronicle: "朝廷特赏基层军士，许都军中多感天恩。",
        },
      ],
    },
  ],
};
