/*
 * 天子蒙尘：献帝模拟器 v0.2.0
 * 全国局势、诸侯动态、人物四维关系与史料时间线数据。
 *
 * 说明：地图为政治态势示意图，不是精确历史地理测绘图；人物数值与动态结果均为游戏化建模。
 */
window.XIAN_WORLD_DATA = {
  version: "0.2.0",
  title: "天下舆图与汉末史料库",

  metricMeta: {
    loyalty: {
      name: "忠诚",
      short: "忠",
      description: "人物对汉室及天子本人的真实认同。高忠诚不等于一定敢于行动。",
      favorableHigh: true,
    },
    fear: {
      name: "恐惧",
      short: "惧",
      description: "人物对曹氏、清洗、战乱和政治失败的畏惧。过高时容易观望、自保或泄密。",
      favorableHigh: false,
    },
    ambition: {
      name: "野心",
      short: "志",
      description: "人物追求权位、地盘和历史功业的强度。它既可能成为动力，也可能演化为威胁。",
      favorableHigh: null,
    },
    interest: {
      name: "利益",
      short: "利",
      description: "人物当前从朝廷合作中得到的官爵、合法性、资源与安全收益。",
      favorableHigh: true,
    },
  },

  sources: [
    {
      id: "hhs_9",
      work: "《后汉书》",
      chapter: "卷九·孝献帝纪",
      author: "范晔",
      url: "https://zh.wikisource.org/zh-hans/%E5%BE%8C%E6%BC%A2%E6%9B%B8/%E5%8D%B79",
      scope: "献帝即位、播迁、建安朝廷与禅让等基本纪年。",
      reliability: "正史本纪",
    },
    {
      id: "hhs_72",
      work: "《后汉书》",
      chapter: "卷七十二·董卓列传",
      author: "范晔",
      url: "https://zh.wikisource.org/zh-hans/%E5%BE%8C%E6%BC%A2%E6%9B%B8/%E5%8D%B772",
      scope: "董卓专政、迁都与汉末中央秩序崩坏。",
      reliability: "正史列传",
    },
    {
      id: "hhs_73",
      work: "《后汉书》",
      chapter: "卷七十三·刘虞公孙瓒陶谦列传",
      author: "范晔",
      url: "https://zh.wikisource.org/zh-hans/%E5%BE%8C%E6%BC%A2%E6%9B%B8/%E5%8D%B773",
      scope: "幽州、公孙瓒、陶谦及北方边地格局。",
      reliability: "正史列传",
    },
    {
      id: "hhs_74a",
      work: "《后汉书》",
      chapter: "卷七十四上·袁绍刘表列传",
      author: "范晔",
      url: "https://zh.wikisource.org/zh-hans/%E5%BE%8C%E6%BC%A2%E6%9B%B8/%E5%8D%B774%E4%B8%8A",
      scope: "袁绍、刘表的政治基础、门第网络与地方经营。",
      reliability: "正史列传",
    },
    {
      id: "sgz_1",
      work: "《三国志》",
      chapter: "卷一·武帝纪",
      author: "陈寿",
      url: "https://zh.wikisource.org/zh-hans/%E4%B8%89%E5%9C%8B%E5%BF%97/%E5%8D%B701",
      scope: "曹操军政活动、奉迎天子、官渡前后大势。",
      reliability: "正史本纪",
    },
    {
      id: "sgz_6",
      work: "《三国志》",
      chapter: "卷六·董二袁刘传",
      author: "陈寿",
      url: "https://zh.wikisource.org/zh-hans/%E4%B8%89%E5%9C%8B%E5%BF%97/%E5%8D%B706",
      scope: "董卓、袁绍、袁术、刘表等诸侯的生平与政治行为。",
      reliability: "正史列传",
    },
    {
      id: "sgz_8",
      work: "《三国志》",
      chapter: "卷八·二公孙陶四张传",
      author: "陈寿",
      url: "https://zh.wikisource.org/zh-hans/%E4%B8%89%E5%9C%8B%E5%BF%97/%E5%8D%B708",
      scope: "张鲁据汉中及其政教体系。",
      reliability: "正史列传",
    },
    {
      id: "sgz_31",
      work: "《三国志》",
      chapter: "卷三十一·刘二牧传",
      author: "陈寿",
      url: "https://zh.wikisource.org/zh-hans/%E4%B8%89%E5%9C%8B%E5%BF%97/%E5%8D%B731",
      scope: "刘焉、刘璋入蜀与益州地方政权。",
      reliability: "正史列传",
    },
    {
      id: "sgz_46",
      work: "《三国志》",
      chapter: "卷四十六·孙破虏讨逆传",
      author: "陈寿",
      url: "https://zh.wikisource.org/zh-hans/%E4%B8%89%E5%9C%8B%E5%BF%97/%E5%8D%B746",
      scope: "孙坚、孙策在江东的军事扩张与政权奠基。",
      reliability: "正史列传",
    },
    {
      id: "zz_61",
      work: "《资治通鉴》",
      chapter: "卷六十一·汉纪五十三",
      author: "司马光",
      url: "https://zh.wikisource.org/zh-hans/%E8%B3%87%E6%B2%BB%E9%80%9A%E9%91%91/%E5%8D%B7061",
      scope: "兴平年间长安局势、关中冲突与天子受制背景。",
      reliability: "编年史",
    },
    {
      id: "zz_62",
      work: "《资治通鉴》",
      chapter: "卷六十二·汉纪五十四",
      author: "司马光",
      url: "https://zh.wikisource.org/zh-hans/%E8%B3%87%E6%B2%BB%E9%80%9A%E9%91%91/%E5%8D%B7062",
      scope: "建安元年东归洛阳、曹操迎驾、迁许与天下诸侯动态。",
      reliability: "编年史",
    },
    {
      id: "zz_63",
      work: "《资治通鉴》",
      chapter: "卷六十三·汉纪五十五",
      author: "司马光",
      url: "https://zh.wikisource.org/zh-hans/%E8%B3%87%E6%B2%BB%E9%80%9A%E9%91%91/%E5%8D%B7063",
      scope: "建安四至五年公孙瓒败亡、官渡战争及北方格局变化。",
      reliability: "编年史",
    },
  ],

  regions: [
    {
      id: "liangzhou",
      name: "凉州",
      short: "凉",
      area: "liangzhou",
      controller: "ma_han",
      capital: "武威",
      stability: 39,
      military: 63,
      courtAttitude: 42,
      importance: "关陇门户",
      summary: "羌胡、豪强与州郡兵力交错，朝廷名号仍有价值，但实际控制薄弱。",
      sourceIds: ["zz_61"],
    },
    {
      id: "guanzhong",
      name: "关中",
      short: "雍",
      area: "guanzhong",
      controller: "fragmented",
      capital: "长安",
      stability: 27,
      military: 46,
      courtAttitude: 51,
      importance: "旧都与西京",
      summary: "战乱后残破，诸将与地方势力并存；若朝廷能够恢复关中，将显著增加正统威望。",
      sourceIds: ["hhs_9", "zz_61", "zz_62"],
    },
    {
      id: "yizhou",
      name: "益州",
      short: "益",
      area: "yizhou",
      controller: "liu_zhang",
      capital: "成都",
      stability: 73,
      military: 56,
      courtAttitude: 47,
      importance: "富庶后方",
      summary: "山川险固、财赋较丰，地方政权重守土，距离许都遥远。",
      sourceIds: ["sgz_31"],
    },
    {
      id: "hanzhong",
      name: "汉中",
      short: "汉",
      area: "hanzhong",
      controller: "zhang_lu",
      capital: "南郑",
      stability: 65,
      military: 48,
      courtAttitude: 33,
      importance: "秦蜀咽喉",
      summary: "张鲁政教合一，扼守秦蜀通道，对中央诏令多为选择性响应。",
      sourceIds: ["sgz_8"],
    },
    {
      id: "jingzhou",
      name: "荆州",
      short: "荆",
      area: "jingzhou",
      controller: "liu_biao",
      capital: "襄阳",
      stability: 77,
      military: 67,
      courtAttitude: 61,
      importance: "南北枢纽",
      summary: "刘表据州自守，士人云集，是汉室可能争取的外援与退路。",
      sourceIds: ["hhs_74a", "sgz_6"],
    },
    {
      id: "jiaozhou",
      name: "交州",
      short: "交",
      area: "jiaozhou",
      controller: "shi_family",
      capital: "广信",
      stability: 69,
      military: 31,
      courtAttitude: 54,
      importance: "远南通道",
      summary: "远离中原大战，地方豪族维持秩序，对汉室仍保留名义尊奉。",
      sourceIds: ["hhs_9"],
    },
    {
      id: "jiangdong",
      name: "江东",
      short: "扬",
      area: "jiangdong",
      controller: "sun_ce",
      capital: "吴郡",
      stability: 57,
      military: 70,
      courtAttitude: 49,
      importance: "东南新锐",
      summary: "孙策迅速扩张，迫切需要朝廷授予官爵以巩固合法性。",
      sourceIds: ["sgz_46"],
    },
    {
      id: "huainan",
      name: "淮南",
      short: "淮",
      area: "huainan",
      controller: "yuan_shu",
      capital: "寿春",
      stability: 43,
      military: 66,
      courtAttitude: 18,
      importance: "僭号风险",
      summary: "袁术占据淮南，资源尚足而政治野心极强，是汉室正统的直接挑战。",
      sourceIds: ["sgz_6", "zz_62"],
    },
    {
      id: "sili_yuzhou",
      name: "司隶·豫州",
      short: "许",
      area: "sili",
      controller: "cao_cao",
      capital: "许都",
      stability: 62,
      military: 84,
      courtAttitude: 72,
      importance: "朝廷中枢",
      summary: "天子与尚书台所在。曹操控制军事与多数行政资源，汉廷法统与曹氏实力相互依存。",
      sourceIds: ["hhs_9", "sgz_1", "zz_62"],
    },
    {
      id: "xuzhou",
      name: "徐州",
      short: "徐",
      area: "xuzhou",
      controller: "lu_bu",
      capital: "下邳",
      stability: 35,
      military: 58,
      courtAttitude: 37,
      importance: "中原东门",
      summary: "吕布、刘备与地方势力反复争夺，城池易手频繁。",
      sourceIds: ["zz_62"],
    },
    {
      id: "qingzhou",
      name: "青州",
      short: "青",
      area: "qingzhou",
      controller: "yuan_shao",
      capital: "临淄",
      stability: 52,
      military: 61,
      courtAttitude: 48,
      importance: "河北东翼",
      summary: "袁氏影响向青州延伸，地方豪强与黄巾余部仍会影响统治。",
      sourceIds: ["hhs_74a", "zz_63"],
    },
    {
      id: "jizhou",
      name: "冀州",
      short: "冀",
      area: "jizhou",
      controller: "yuan_shao",
      capital: "邺",
      stability: 75,
      military: 89,
      courtAttitude: 53,
      importance: "河北核心",
      summary: "人口、粮赋与门生故吏集中，是当时最强大的地方政治集团之一。",
      sourceIds: ["hhs_74a", "sgz_6", "zz_63"],
    },
    {
      id: "bingzhou",
      name: "并州",
      short: "并",
      area: "bingzhou",
      controller: "fragmented",
      capital: "晋阳",
      stability: 33,
      military: 52,
      courtAttitude: 43,
      importance: "北地兵源",
      summary: "郡县、豪强与胡骑势力交错，名义归属与实际控制经常分离。",
      sourceIds: ["zz_63"],
    },
    {
      id: "youzhou",
      name: "幽州",
      short: "幽",
      area: "youzhou",
      controller: "gongsun_zan",
      capital: "蓟",
      stability: 44,
      military: 68,
      courtAttitude: 39,
      importance: "北疆与乌桓",
      summary: "公孙瓒与袁绍争夺北方，乌桓、边郡与地方军阀共同影响格局。",
      sourceIds: ["hhs_73", "zz_63"],
    },
  ],

  controllers: {
    cao_cao: { name: "曹操", color: "#657a8e", text: "#edf6ff" },
    yuan_shao: { name: "袁绍", color: "#95794b", text: "#fff7db" },
    yuan_shu: { name: "袁术", color: "#82404d", text: "#ffe9ed" },
    liu_biao: { name: "刘表", color: "#4d7763", text: "#e8fff2" },
    sun_ce: { name: "孙策", color: "#3f7c83", text: "#e6fdff" },
    liu_zhang: { name: "刘璋", color: "#6d7650", text: "#f6f8e2" },
    zhang_lu: { name: "张鲁", color: "#6a5e86", text: "#f3edff" },
    ma_han: { name: "马腾·韩遂", color: "#896247", text: "#fff0e1" },
    lu_bu: { name: "吕布", color: "#854d3d", text: "#fff0e8" },
    gongsun_zan: { name: "公孙瓒", color: "#7c7f94", text: "#f3f4ff" },
    shi_family: { name: "士氏", color: "#50766f", text: "#eafffa" },
    fragmented: { name: "群雄割据", color: "#5f5750", text: "#f3e8dc" },
  },

  lords: [
    {
      id: "cao_cao",
      name: "曹操",
      title: "司空·录尚书事",
      seat: "许都",
      regions: ["sili_yuzhou"],
      power: 82,
      courtNeed: 88,
      expansion: 79,
      caution: 84,
      agenda: ["整合中枢", "征讨吕布", "牵制袁绍"],
      sourceIds: ["sgz_1", "zz_62"],
    },
    {
      id: "yuan_shao",
      name: "袁绍",
      title: "冀州牧",
      seat: "邺",
      regions: ["jizhou", "qingzhou"],
      power: 90,
      courtNeed: 63,
      expansion: 72,
      caution: 58,
      agenda: ["兼并幽州", "扩张河北", "争夺朝廷名分"],
      sourceIds: ["hhs_74a", "sgz_6", "zz_63"],
    },
    {
      id: "yuan_shu",
      name: "袁术",
      title: "后将军",
      seat: "寿春",
      regions: ["huainan"],
      power: 67,
      courtNeed: 22,
      expansion: 78,
      caution: 34,
      agenda: ["搜罗符瑞", "压榨淮南", "寻求帝号"],
      sourceIds: ["sgz_6", "zz_62"],
    },
    {
      id: "liu_biao",
      name: "刘表",
      title: "荆州牧",
      seat: "襄阳",
      regions: ["jingzhou"],
      power: 73,
      courtNeed: 58,
      expansion: 31,
      caution: 87,
      agenda: ["保境安民", "招纳士人", "观望中原"],
      sourceIds: ["hhs_74a", "sgz_6"],
    },
    {
      id: "sun_ce",
      name: "孙策",
      title: "讨逆将军",
      seat: "吴郡",
      regions: ["jiangdong"],
      power: 62,
      courtNeed: 78,
      expansion: 93,
      caution: 43,
      agenda: ["平定江东", "获取朝廷官爵", "摆脱袁术"],
      sourceIds: ["sgz_46"],
    },
    {
      id: "liu_zhang",
      name: "刘璋",
      title: "益州牧",
      seat: "成都",
      regions: ["yizhou"],
      power: 58,
      courtNeed: 49,
      expansion: 20,
      caution: 81,
      agenda: ["守土", "平衡益州豪强", "避免中原战争"],
      sourceIds: ["sgz_31"],
    },
    {
      id: "zhang_lu",
      name: "张鲁",
      title: "汉中割据者",
      seat: "南郑",
      regions: ["hanzhong"],
      power: 45,
      courtNeed: 36,
      expansion: 38,
      caution: 73,
      agenda: ["稳固汉中", "控制栈道", "维持政教秩序"],
      sourceIds: ["sgz_8"],
    },
    {
      id: "ma_han",
      name: "马腾·韩遂",
      title: "凉州诸将",
      seat: "西凉",
      regions: ["liangzhou"],
      power: 61,
      courtNeed: 46,
      expansion: 56,
      caution: 48,
      agenda: ["争夺关中", "安抚羌胡", "借诏书自重"],
      sourceIds: ["zz_61"],
    },
  ],

  characterProfiles: {
    liu_xie: { loyalty: 100, fear: 52, ambition: 82, interest: 100, archetype: "受制天子", assessment: "法统即自身，恢复皇权与保存宗庙是同一目标。", sourceIds: ["hhs_9", "zz_62"] },
    empress_fu: { loyalty: 90, fear: 66, ambition: 31, interest: 73, archetype: "宫中支柱", assessment: "忠于皇室且重视安全，局势恶化时更倾向谨慎联络而非公开对抗。", sourceIds: ["hhs_9"] },
    dong_cheng: { loyalty: 83, fear: 57, ambition: 58, interest: 61, archetype: "冒险忠臣", assessment: "愿替汉室承担风险，但容易高估密谋的保密性与执行力。", sourceIds: ["hhs_9", "zz_62"] },
    yang_biao: { loyalty: 74, fear: 63, ambition: 36, interest: 55, archetype: "持重旧臣", assessment: "重名分与礼制，愿维护皇权，却会避免让家族卷入毫无胜算的豪赌。", sourceIds: ["hhs_9"] },
    xun_yu: { loyalty: 71, fear: 38, ambition: 47, interest: 77, archetype: "秩序维护者", assessment: "认同汉室秩序，同时依赖曹操重建行政；更支持制度恢复而非宫廷密谋。", sourceIds: ["sgz_1"] },
    cao_cao: { loyalty: 19, fear: 17, ambition: 96, interest: 91, archetype: "挟持型盟友", assessment: "需要汉廷法统号令天下，但不会允许皇权脱离其军政控制。", sourceIds: ["sgz_1", "zz_62"] },
    yuan_shao: { loyalty: 33, fear: 24, ambition: 91, interest: 72, archetype: "河北雄主", assessment: "重视门第与名望，愿借朝廷官爵扩大声势，但不接受许都实质节制。", sourceIds: ["hhs_74a", "sgz_6"] },
    yuan_shu: { loyalty: 6, fear: 19, ambition: 99, interest: 26, archetype: "僭号野心家", assessment: "对汉室名分以利用与取代为主，现实利益不足时极易公开背离。", sourceIds: ["sgz_6", "zz_62"] },
    liu_biao: { loyalty: 57, fear: 49, ambition: 48, interest: 62, archetype: "守成宗亲", assessment: "愿维持汉室门面，但首要目标始终是保全荆州与本州秩序。", sourceIds: ["hhs_74a", "sgz_6"] },
    sun_ce: { loyalty: 28, fear: 21, ambition: 94, interest: 82, archetype: "江东新锐", assessment: "急需朝廷承认以巩固江东，却不会接受过度约束。", sourceIds: ["sgz_46"] },
  },

  timeline: [
    { id: "t189_enthronement", year: 189, month: 9, title: "刘协即皇帝位", summary: "董卓废少帝，立陈留王刘协，是为汉献帝。", sourceIds: ["hhs_9", "hhs_72"], gameNote: "玩家政治困境的起点：法统来自被权臣操控的废立。" },
    { id: "t190_move_changan", year: 190, month: 2, title: "迁都长安", summary: "董卓迫使朝廷西迁，洛阳宫室与中央秩序遭到严重破坏。", sourceIds: ["hhs_9", "hhs_72"], gameNote: "解释国库、宫廷安全与中央执行力的长期低值。" },
    { id: "t192_dong_zhuo_death", year: 192, month: 4, title: "董卓被诛", summary: "王允、吕布诛董卓，随后李傕、郭汜反攻长安，天子继续受制。", sourceIds: ["hhs_9", "hhs_72"], gameNote: "汉廷摆脱一个权臣，却未恢复独立。" },
    { id: "t195_east_return", year: 195, month: 7, title: "车驾东归", summary: "献帝离开长安，在诸将护送与争斗中东还洛阳。", sourceIds: ["hhs_9", "zz_61", "zz_62"], gameNote: "董承等人的政治资本来源，也是朝廷旧臣网络的基础。" },
    { id: "t196_xu", year: 196, month: 9, title: "曹操迎天子，迁都许", summary: "曹操控制中枢，录尚书事；朝廷在许县重新运转。", sourceIds: ["hhs_9", "sgz_1", "zz_62"], gameNote: "本作首发剧本的直接开局背景。" },
    { id: "t197_wancheng", year: 197, month: 1, title: "宛城之败", summary: "曹操南征张绣失利，许都军政集团短期承压。", sourceIds: ["sgz_1", "zz_62"], gameNote: "皇帝可能借曹氏受挫争取军务监督，也可能选择慰军维持合作。" },
    { id: "t197_yuan_shu", year: 197, month: 2, title: "袁术僭号", summary: "袁术在淮南称帝，汉廷正统遭遇直接挑战。", sourceIds: ["sgz_6", "zz_62"], gameNote: "可触发讨逆诏书、江东策反与诸侯合法性竞争。" },
    { id: "t198_xiapi", year: 198, month: 12, title: "吕布败亡", summary: "曹操攻破下邳，徐州形势转入曹氏主导。", sourceIds: ["sgz_1", "zz_62"], gameNote: "曹氏军事实力与对朝廷的控制能力同步上升。" },
    { id: "t199_gongsun", year: 199, month: 3, title: "公孙瓒败亡", summary: "袁绍兼并幽州大部，河北力量达到高峰。", sourceIds: ["hhs_73", "zz_63"], gameNote: "全国战略重心转向曹袁对峙。" },
    { id: "t200_guandu", year: 200, month: 10, title: "官渡决战", summary: "曹操击败袁绍主力，北方格局开始逆转。", sourceIds: ["sgz_1", "zz_63"], gameNote: "若扩展长剧本，可作为汉廷选择站队或制衡的重大节点。" },
    { id: "t220_abdication", year: 220, month: 10, title: "献帝禅位", summary: "曹丕代汉，刘协受封山阳公，东汉终结。", sourceIds: ["hhs_9"], gameNote: "主历史线的终点，也可作为终局剧本。" },
  ],

  eventSourceMap: {
    arrival_xu: ["hhs_9", "sgz_1", "zz_62"], seal_and_edicts: ["hhs_9", "zz_62"], yuan_shu_ambition: ["sgz_6", "zz_62"], palace_guard: ["hhs_9"], northern_envoy: ["hhs_74a", "sgz_6"], xun_yu_memorial: ["sgz_1"], wan_crisis: ["sgz_1", "zz_62"], final_pressure: ["hhs_9", "sgz_1"], grain_price: ["zz_62"], forged_edict: ["hhs_9"], palace_rumor: ["hhs_9", "hhs_74a"], tax_petition: ["zz_62"], scholar_recommendation: ["sgz_1"], seal_ceremony: ["hhs_9"], cao_gift: ["sgz_1"],
  },

  dynamicTemplates: {
    cao_cao: ["整饬许都军政，要求各郡军粮与名籍统一上报。", "遣将清剿近郡盗贼，借朝廷名义重申州郡秩序。", "召集谋臣评估河北动向，并加强黄河沿线戒备。", "向朝廷请授军职与节制权限，以便统合诸军。"],
    yuan_shao: ["扩充河北兵粮，门生故吏向青、幽二州继续延伸。", "遣使奉表朝廷，同时要求提高官爵与督州名义。", "调集诸军压迫公孙瓒，河北战线明显升温。", "召集审配、逢纪等议事，内部对南下时机意见不一。"],
    yuan_shu: ["搜罗符瑞并僭用礼仪，淮南属吏争相迎合。", "加征粮赋以扩军，地方稳定与民心继续下降。", "试图离间孙策与朝廷，防止江东获得独立名分。", "遣使试探诸侯对帝号的态度，公开野心进一步上升。"],
    liu_biao: ["整顿荆州郡县，继续以守成为主，不轻易介入中原。", "招纳北来士人，襄阳文士与地方豪族影响扩大。", "接见朝廷使者，但对出兵与输粮要求保持含糊。", "加强江夏与南阳戒备，防范淮南和江东势力。"],
    sun_ce: ["率军攻取江东郡县，以快速军事行动扩大控制。", "遣使请求朝廷官爵，希望摆脱袁术旧部身份。", "整编降众与地方豪强，江东政权基础逐渐稳固。", "将兵锋指向邻近郡县，江东扩张速度引起各方警惕。"],
    liu_zhang: ["益州继续闭境守土，地方豪强与州府维持脆弱平衡。", "成都筹措粮赋，对中原诏令只作礼节性回应。", "派吏安抚郡县，避免流民与宗族武装扩大。"],
    zhang_lu: ["整顿汉中栈道与关隘，对秦蜀商旅加强控制。", "以政教体系安抚百姓，拒绝外部势力深入汉中。", "试探益州与关中的变化，保持两面观望。"],
    ma_han: ["凉州诸将重新集结部众，关中道路出现兵马调动。", "与羌胡豪帅议盟，向朝廷请求官号以自重。", "马腾与韩遂关系时合时离，西部局势仍难稳定。"],
  },
};
